use_frameworks!

platform :ios, '9.0'

target 'UnitAudioConverter_Example' do
  pod 'UnitAudioConverter', :path => '../'

  target 'UnitAudioConverter_Tests' do
    inherit! :search_paths

    
  end
end
